### ISSUE TITLE
Paste typo in license

### ISSUE THREAD

**Issue by vietjtnguyen** [dkogan/mrcal#1]
Looks like there's an accidental paste typo in the license file: https://github.com/dkogan/mrcal/blob/95f6fdf077df45f619a700aec02d88bd48585918/LICENSE#L145

**Comment by dkogan** [comment]
You get issue #1! Thanks. Apparently I must have `curl something >& LICENSE`. Fixed in https://github.com/dkogan/mrcal/commit/7dc7631ab0e7cd8d5aad607654fb4f59885a93c2
