### ISSUE TITLE
expand_intrinsics does not decrease higher order distortion coefficient magnitude

### ISSUE THREAD

**Issue by mcm001** [dkogan/mrcal#14]
[Here](https://github.com/dkogan/mrcal/blob/4220264908a9bbc21951540e9252b889966c10bf/mrcal-calibrate-cameras#L533), you try to reduce the magnitude of elements 5:8 of the seed distortions. But at least with mrcal 2.4.1-1jammy1, this does not change the distortion array (ie, it stays as `array([[-2.99872679e-07,  2.76209510e-07,  4.95254637e-07,  3.46701237e-07,  3.11457662e-07, -1.01066852e-08, -2.02589460e-07, -5.68497143e-07]])`) for an OPENCV8 model. Under debugger, you can see newDistortions.shape is actually (1, 8) and not (,8), so `newDistortions[5:8]` is an empty array. Did you mean `newDistortions[:,5:8]`?

![image](https://github.com/dkogan/mrcal/assets/29715865/dc8a8d4d-bf73-407f-ad61-4a579945896e)

**Comment by dkogan** [comment]
Thanks much for finding this. I looked through version control, and apparently this has never worked as intended. I pushed the fix to git, but obviously it has never actually been tested. If you cherry-pick this and see any problems, let me know. I'll run experiments before the next release at the latest, but it may not be for a while.
