### ISSUE TITLE
splined models

### ISSUE THREAD

**Issue by Mr-ZhuJun** [dkogan/mrcal#17]
splined models. Described here:

  http://mrcal.secretsauce.net/splined-models.html
  
  Hello, author, this is a great work, I would like to ask how I use this parametric model, how do I dedistort the image points, how do I triangulate it, because there is no projection matrix.

**Comment by dkogan** [comment]
Did you read the documentation? Everything is described there. Are you asking about the equations or about the code?

Generally everything involving homogeneous coordinates (projection matrices, etc) is poisonous and should be avoided. For instance, what do you do with very wide lenses near 90deg off the "forward" direction.

**Comment by dkogan** [comment]
Closing. Reopen if there are more questions
