### ISSUE TITLE
Corners.vnl in tour link is dead

### ISSUE THREAD

**Issue by mcm001** [dkogan/mrcal#33]
Hello! Right now, `2022-11-05--dtla-overpass--samyang--alpha7/2-f22-infinity/corners.vnl`, linked from https://mrcal.secretsauce.net/tour-initial-calibration.html and https://github.com/dkogan/mrcal/blob/master/doc/tour-initial-calibration.org , is currently 403 for me. It looks like https://mrcal.secretsauce.net/docs-default/external/2022-11-05--dtla-overpass--samyang--alpha7/2-f22-infinity/corners-rad1500.vnl is accessible as of 2024-12-01 though.

**Comment by dkogan** [comment]
Thanks for the report. Fixed.
