### ISSUE TITLE
Using ChAruco boards to get more image coverage near corners

### ISSUE THREAD

**Issue by MafteiAlbert-Alexandru** [dkogan/mrcal#9]
First of all, thank you for this amazing piece of software you have provided for free. 
Second, have you considered using ChAruco boards to get more coverage around the corners?

**Comment by dkogan** [comment]
Hi. Thanks.

I don't use charuco boards, but mrcal could certainly use them. "mrcal" itself doesn't use any kind of board: it ingests corner detections from some other tool. So if you take charuco images, and use some detector to process them, and report the corner coordinates, mrcal will happily use them. See here:

http://mrcal.secretsauce.net/recipes.html#non-mrgingham-detector

**Comment by dkogan** [comment]
Closing the issue. Feel free to reopen if there's anything for me to do here.
